version: "3.9"
services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "krezon"
      POSTGRES_PASSWORD: "1111"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  restapi:
    image: restapi
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "krezon"
      POSTGRES_PASSWORD: "1111"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "8080:8080"
    
